source = /home/otsnd/.cache/wal/colors-hyprland.conf

# BACKGROUND
background {
    monitor = DP-2
    #path = screenshot
    path = ~/.config/hypr/current-wallpaper
    color = $color1
    blur_passes = 2
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

listener {
    timeout = 300  # 5 minutes in seconds
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# GENERAL
general {
    no_fade_in = false
    no_fade_out = false
    hide_cursor = false
    grace = 1
    disable_loading_bar = false
}

# INPUT FIELD
input-field {
    monitor = DP-2
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.2)
    font_color = $color6
    fade_on_empty = false
    rounding = -1
    check_color = $color9
    placeholder_text = password
    hide_input = false
    position = 0, -300
    halign = center
    valign = center
}

# DATE
label {
  monitor = DP-2
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = $color5
  font_size = 20
  font_family = JetBrains Mono
  position = 0, 330
  halign = center
  valign = center
}

# TIME
label {
  monitor = DP-2
  text = cmd[update:1000] echo "$(date +"%-I:%M")"
  #color = rgba(242, 243, 244, 0.75)
  color = $color5
  font_size = 190
  font_family = JetBrains Mono Extrabold
  position = 0, 200
  halign = center
  valign = center
}

# Profile Picture
image {
    monitor = DP-2
    path = /home/otsnd/Pictures/profilepicture/1315698280811.jpg
    size = 130
    border_size = 2
    border_color = $color6
    position = 0, -100
    halign = center
    valign = center
}

# CURRENT SONG
label {
    monitor = DP-2
    text = cmd[update:1000] echo "$(/home/otsnd/.config/hypr/spotify-status.sh)"
    color = $color6
    font_size = 12
    font_family = JetBrainsMono Nerd Font
    position = 0, 60
    halign = center
    valign = bottom
}

label {
    monitor = DP-2
    text = cmd[update:1000] echo "$(whoami)"
    color = $color6
    font_size = 14
    font_family = JetBrains Mono
    position = 0, -200
    halign = center
    valign = center
}

label {
    monitor = DP-2
    text = cmd[update:1000] echo "$(/home/justin/Documents/Scripts/battery.sh)"
    color = $foreground
    font_size = 24
    font_family = JetBrains Mono
    position = -90, -10
    halign = right
    valign = top
}

label {
    monitor = DP-2
    text = cmd[update:1000] echo "$(/home/justin/Documents/Scripts/network-status.sh)"
    color = $foreground
    font_size = 24
    font_family = JetBrains Mono
    position = -20, -10
    halign = right
    valign = top
}
