general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display
}

listener {
    timeout = 1200                               # 20 minutes
    on-timeout = loginctl lock-session           # lock screen
    on-resume = swayosd-server &
}

listener {
    timeout = 1500                               # 25 minutes
    on-timeout = hyprctl dispatch dpms off       # turn off screen
    on-resume = hyprctl dispatch dpms on         # turn screen back on
}